FROM container-registry.oracle.com/database/express:21.3.0-xe

# Copy initialization script
COPY ../../src/main/webapp/WEB-INF/sql/blank_web_oracle.sql /docker-entrypoint-initdb.d/

# Expose Oracle ports
EXPOSE 1521 5500