package sk.iway.iwcm.system.metadata;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDDocumentInformation;

import sk.iway.iwcm.Constants;
import sk.iway.iwcm.Logger;
import sk.iway.iwcm.Tools;

/**
 * Utility class for cleaning sensitive metadata from generated files.
 * Currently supports PDF files generated by PD4ML (pdf-gen).
 */
public class MetadataCleanerPdf {

    private MetadataCleanerPdf() {
        // utility class
    }

    /**
     * Post-process a generated PDF to override Creator and Producer metadata fields,
     * preventing disclosure of the PD4ML library name and version in PDF metadata.
     * The replacement value is taken from the pdfAuthorName configuration constant.
     *
     * @param pdfOut the ByteArrayOutputStream containing the generated PDF bytes
     * @param output the final OutputStream to write the processed PDF to
     * @throws IOException if reading or writing fails
     */
    public static void removeMetadata(ByteArrayOutputStream pdfOut, OutputStream output) throws IOException {
        String authorName = Tools.getStringValue(Constants.getString("pdfAuthorName"), "");
        try (PDDocument document = Loader.loadPDF(pdfOut.toByteArray())) {
            PDDocumentInformation info = document.getDocumentInformation();
            info.setCreator(authorName);
            info.setProducer(authorName);
            document.save(output);
        } catch (Exception e) {
            Logger.error(MetadataCleanerPdf.class, e);
            // Fall back to writing the unmodified PDF
            pdfOut.writeTo(output);
        }
    }
}
