<%
sk.iway.iwcm.Encoding.setResponseEnc(request, response, "text/html");
%><%@ page pageEncoding="utf-8" import="sk.iway.iwcm.*" %><%@
taglib prefix="iwcm" uri="/WEB-INF/iwcm.tld" %><iwcm:checkLogon admin="true" perms="modUpdate"/>
<%@ include file="/admin/layout_top.jsp" %>

<h1>OLD admin jsp example</h1>

<p>Used in autotests</p>

<p>Session: <input type="text" value="<%=session.getId()%>" id="sessionId" /></p>

<style type="text/css">
    h1 {
        scroll-margin-top: 2em;
    }
</style>

<h1 id="education-dashboard">Dashboard</h1>

<p>Dashboard lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit augue sit amet tellus egestas, a cursus enim gravida. Pellentesque fringilla arcu neque, vitae posuere est volutpat quis. Quisque tincidunt mollis vulputate. Nam pretium efficitur mauris dictum iaculis. Donec commodo eu eros ac pharetra. Etiam ultricies et velit id imperdiet. Curabitur consequat tortor sit amet dui commodo tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Integer a nibh vel risus laoreet fermentum. Nulla ac rhoncus dolor. Morbi eget erat finibus, interdum tortor ac, dapibus dui. Ut nec molestie enim. Nulla metus lectus, luctus quis ornare eu, maximus in lectus. Sed blandit dictum finibus. Donec efficitur, neque id iaculis venenatis, erat libero tempor augue, consectetur consectetur quam libero et orci. Praesent molestie enim id augue rhoncus, mollis pellentesque enim porttitor. Curabitur a lorem varius, pellentesque quam et, rutrum enim. Nullam accumsan diam purus, id blandit nisi aliquam id. Pellentesque blandit ante non ultrices eleifend.</p>
<p>Nunc sed consequat ipsum. Aenean consequat mattis orci, sed commodo orci tincidunt tempus. Aenean vitae dui lacus. Phasellus justo tortor, aliquet id diam eu, mollis lobortis sapien. Cras tempus nulla purus. Etiam eu tempor urna, non eleifend orci. Fusce blandit ligula sed dolor pellentesque posuere.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit augue sit amet tellus egestas, a cursus enim gravida. Pellentesque fringilla arcu neque, vitae posuere est volutpat quis. Quisque tincidunt mollis vulputate. Nam pretium efficitur mauris dictum iaculis. Donec commodo eu eros ac pharetra. Etiam ultricies et velit id imperdiet. Curabitur consequat tortor sit amet dui commodo tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Integer a nibh vel risus laoreet fermentum. Nulla ac rhoncus dolor. Morbi eget erat finibus, interdum tortor ac, dapibus dui. Ut nec molestie enim. Nulla metus lectus, luctus quis ornare eu, maximus in lectus. Sed blandit dictum finibus. Donec efficitur, neque id iaculis venenatis, erat libero tempor augue, consectetur consectetur quam libero et orci. Praesent molestie enim id augue rhoncus, mollis pellentesque enim porttitor. Curabitur a lorem varius, pellentesque quam et, rutrum enim. Nullam accumsan diam purus, id blandit nisi aliquam id. Pellentesque blandit ante non ultrices eleifend.</p>
<p>Nunc sed consequat ipsum. Aenean consequat mattis orci, sed commodo orci tincidunt tempus. Aenean vitae dui lacus. Phasellus justo tortor, aliquet id diam eu, mollis lobortis sapien. Cras tempus nulla purus. Etiam eu tempor urna, non eleifend orci. Fusce blandit ligula sed dolor pellentesque posuere.</p>

<h1 id="education-courses">Courses</h1>

<p>Courses integer a nibh vel risus laoreet fermentum. Nulla ac rhoncus dolor. Morbi eget erat finibus, interdum tortor ac, dapibus dui. Ut nec molestie enim. Nulla metus lectus, luctus quis ornare eu, maximus in lectus. Sed blandit dictum finibus. Donec efficitur, neque id iaculis venenatis, erat libero tempor augue, consectetur consectetur quam libero et orci. Praesent molestie enim id augue rhoncus, mollis pellentesque enim porttitor. Curabitur a lorem varius, pellentesque quam et, rutrum enim. Nullam accumsan diam purus, id blandit nisi aliquam id. Pellentesque blandit ante non ultrices eleifend.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit augue sit amet tellus egestas, a cursus enim gravida. Pellentesque fringilla arcu neque, vitae posuere est volutpat quis. Quisque tincidunt mollis vulputate. Nam pretium efficitur mauris dictum iaculis. Donec commodo eu eros ac pharetra. Etiam ultricies et velit id imperdiet. Curabitur consequat tortor sit amet dui commodo tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Nunc sed consequat ipsum. Aenean consequat mattis orci, sed commodo orci tincidunt tempus. Aenean vitae dui lacus. Phasellus justo tortor, aliquet id diam eu, mollis lobortis sapien. Cras tempus nulla purus. Etiam eu tempor urna, non eleifend orci. Fusce blandit ligula sed dolor pellentesque posuere.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit augue sit amet tellus egestas, a cursus enim gravida. Pellentesque fringilla arcu neque, vitae posuere est volutpat quis. Quisque tincidunt mollis vulputate. Nam pretium efficitur mauris dictum iaculis. Donec commodo eu eros ac pharetra. Etiam ultricies et velit id imperdiet. Curabitur consequat tortor sit amet dui commodo tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Integer a nibh vel risus laoreet fermentum. Nulla ac rhoncus dolor. Morbi eget erat finibus, interdum tortor ac, dapibus dui. Ut nec molestie enim. Nulla metus lectus, luctus quis ornare eu, maximus in lectus. Sed blandit dictum finibus. Donec efficitur, neque id iaculis venenatis, erat libero tempor augue, consectetur consectetur quam libero et orci. Praesent molestie enim id augue rhoncus, mollis pellentesque enim porttitor. Curabitur a lorem varius, pellentesque quam et, rutrum enim. Nullam accumsan diam purus, id blandit nisi aliquam id. Pellentesque blandit ante non ultrices eleifend.</p>
<p>Nunc sed consequat ipsum. Aenean consequat mattis orci, sed commodo orci tincidunt tempus. Aenean vitae dui lacus. Phasellus justo tortor, aliquet id diam eu, mollis lobortis sapien. Cras tempus nulla purus. Etiam eu tempor urna, non eleifend orci. Fusce blandit ligula sed dolor pellentesque posuere.</p>

<h1 id="education-course-requests">Requests</h1>

<p>Requests nunc sed consequat ipsum. Aenean consequat mattis orci, sed commodo orci tincidunt tempus. Aenean vitae dui lacus. Phasellus justo tortor, aliquet id diam eu, mollis lobortis sapien. Cras tempus nulla purus. Etiam eu tempor urna, non eleifend orci. Fusce blandit ligula sed dolor pellentesque posuere.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit augue sit amet tellus egestas, a cursus enim gravida. Pellentesque fringilla arcu neque, vitae posuere est volutpat quis. Quisque tincidunt mollis vulputate. Nam pretium efficitur mauris dictum iaculis. Donec commodo eu eros ac pharetra. Etiam ultricies et velit id imperdiet. Curabitur consequat tortor sit amet dui commodo tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Integer a nibh vel risus laoreet fermentum. Nulla ac rhoncus dolor. Morbi eget erat finibus, interdum tortor ac, dapibus dui. Ut nec molestie enim. Nulla metus lectus, luctus quis ornare eu, maximus in lectus. Sed blandit dictum finibus. Donec efficitur, neque id iaculis venenatis, erat libero tempor augue, consectetur consectetur quam libero et orci. Praesent molestie enim id augue rhoncus, mollis pellentesque enim porttitor. Curabitur a lorem varius, pellentesque quam et, rutrum enim. Nullam accumsan diam purus, id blandit nisi aliquam id. Pellentesque blandit ante non ultrices eleifend.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit augue sit amet tellus egestas, a cursus enim gravida. Pellentesque fringilla arcu neque, vitae posuere est volutpat quis. Quisque tincidunt mollis vulputate. Nam pretium efficitur mauris dictum iaculis. Donec commodo eu eros ac pharetra. Etiam ultricies et velit id imperdiet. Curabitur consequat tortor sit amet dui commodo tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Integer a nibh vel risus laoreet fermentum. Nulla ac rhoncus dolor. Morbi eget erat finibus, interdum tortor ac, dapibus dui. Ut nec molestie enim. Nulla metus lectus, luctus quis ornare eu, maximus in lectus. Sed blandit dictum finibus. Donec efficitur, neque id iaculis venenatis, erat libero tempor augue, consectetur consectetur quam libero et orci. Praesent molestie enim id augue rhoncus, mollis pellentesque enim porttitor. Curabitur a lorem varius, pellentesque quam et, rutrum enim. Nullam accumsan diam purus, id blandit nisi aliquam id. Pellentesque blandit ante non ultrices eleifend.</p>
<p>Nunc sed consequat ipsum. Aenean consequat mattis orci, sed commodo orci tincidunt tempus. Aenean vitae dui lacus. Phasellus justo tortor, aliquet id diam eu, mollis lobortis sapien. Cras tempus nulla purus. Etiam eu tempor urna, non eleifend orci. Fusce blandit ligula sed dolor pellentesque posuere.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit augue sit amet tellus egestas, a cursus enim gravida. Pellentesque fringilla arcu neque, vitae posuere est volutpat quis. Quisque tincidunt mollis vulputate. Nam pretium efficitur mauris dictum iaculis. Donec commodo eu eros ac pharetra. Etiam ultricies et velit id imperdiet. Curabitur consequat tortor sit amet dui commodo tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Integer a nibh vel risus laoreet fermentum. Nulla ac rhoncus dolor. Morbi eget erat finibus, interdum tortor ac, dapibus dui. Ut nec molestie enim. Nulla metus lectus, luctus quis ornare eu, maximus in lectus. Sed blandit dictum finibus. Donec efficitur, neque id iaculis venenatis, erat libero tempor augue, consectetur consectetur quam libero et orci. Praesent molestie enim id augue rhoncus, mollis pellentesque enim porttitor. Curabitur a lorem varius, pellentesque quam et, rutrum enim. Nullam accumsan diam purus, id blandit nisi aliquam id. Pellentesque blandit ante non ultrices eleifend.</p>
<p>Nunc sed consequat ipsum. Aenean consequat mattis orci, sed commodo orci tincidunt tempus. Aenean vitae dui lacus. Phasellus justo tortor, aliquet id diam eu, mollis lobortis sapien. Cras tempus nulla purus. Etiam eu tempor urna, non eleifend orci. Fusce blandit ligula sed dolor pellentesque posuere.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit augue sit amet tellus egestas, a cursus enim gravida. Pellentesque fringilla arcu neque, vitae posuere est volutpat quis. Quisque tincidunt mollis vulputate. Nam pretium efficitur mauris dictum iaculis. Donec commodo eu eros ac pharetra. Etiam ultricies et velit id imperdiet. Curabitur consequat tortor sit amet dui commodo tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Integer a nibh vel risus laoreet fermentum. Nulla ac rhoncus dolor. Morbi eget erat finibus, interdum tortor ac, dapibus dui. Ut nec molestie enim. Nulla metus lectus, luctus quis ornare eu, maximus in lectus. Sed blandit dictum finibus. Donec efficitur, neque id iaculis venenatis, erat libero tempor augue, consectetur consectetur quam libero et orci. Praesent molestie enim id augue rhoncus, mollis pellentesque enim porttitor. Curabitur a lorem varius, pellentesque quam et, rutrum enim. Nullam accumsan diam purus, id blandit nisi aliquam id. Pellentesque blandit ante non ultrices eleifend.</p>
<p>Nunc sed consequat ipsum. Aenean consequat mattis orci, sed commodo orci tincidunt tempus. Aenean vitae dui lacus. Phasellus justo tortor, aliquet id diam eu, mollis lobortis sapien. Cras tempus nulla purus. Etiam eu tempor urna, non eleifend orci. Fusce blandit ligula sed dolor pellentesque posuere.</p>

<%@ include file="/admin/layout_bottom.jsp" %>