leftMenuNameKey=components.enumerations
itemKey=cmp_enumerations
requireConstantsKey=
userItem=true
menuOrder=200
leftMenuLink=/apps/enumeration/admin/
isCustom=false
defaultDisabled=true
icon=list
