package sk.iway.iwcm.doc;

import javax.servlet.http.HttpServletRequest;

/**
 * Interface for custom navbar implementations.
 * Clients can implement this interface to provide custom navbar formatting.
 * The implementation class name should be set in Constants.getString("navbarDefaultType").
 */
public interface NavbarInterface {

    /**
     * Generates navbar (breadcrumb navigation)
     * @param groupId - ID of the directory/group
     * @param docId - ID of current web page
     * @param request - HTTP request
     * @return HTML code for breadcrumb navigation
     */
    String getNavbar(int groupId, int docId, HttpServletRequest request);

    /**
     * Generates navbar for a document if current doc is not default doc of last group in navbar
     * This will be added to navbar generated by getNavbar method
     * @param doc - document details
     * @param navbarHtml - existing navbar HTML
     * @param request
     * @return
     */
    String getNavbarForNonDefaultDoc(DocDetails doc, String navbarHtml, HttpServletRequest request);
}
